---
- name: Tableau Data Extraction and Validation
  hosts: localhost
  gather_facts: false

  vars_files:
  - "config/tableau_config.yml"

  vars:
    vault_environment: "{{ env }}"
    secrets:
    - namespace: vault_credentials
      app_code: "{{ survey_appcode | upper }}"
      vault_env: "{{ env }}"
      vault_secret_path: "{{ vault_secret_path }}/credentials"
      vault_role_id: "{{ vault_role_id }}"
      vault_secret_id: "{{ vault_secret_id }}"

  roles:
  - { role: rbc_common.hashicorp_vault.vault_init }

  tasks:
  - name: Include Tableau extraction tasks
    ansible.builtin.include_tasks:
      file: ansible/playbooks/extract_tableau_data.yml
