---
app_controller_templates:
- name: "{{ .Values.HELIOS_APP_CODE }}_{{ .Values.HELIOS_APP_NAME }}"
  job_type: run
  playbook: main.yml
  inventory: "{{ .Values.HELIOS_APP_CODE }}_{{ .Values.HELIOS_APP_NAME }}"
  project: "{{ .Values.HELIOS_APP_CODE }}_{{ .Values.HELIOS_APP_NAME }}"
  survey_enabled: true
  ask_credential_on_launch: true
  description: "Tableau Data Extraction"
  state: "present"
  credentials:
  - "{{ .Values.HELIOS_APP_CODE }}_HashiCorp_Vault_AppRoles"
  extra_vars:
    vault_environment: "{{ .Values.VAULT_ENV }}"
